"""Milestone 10 -- governance: a model card that cannot go stale, and a CI gate.

Two ideas here, both deliberately unglamorous:

1. **The model card is generated, not written.** A hand-written card starts
   accurate and drifts the moment anyone retrains. This one is assembled from the
   artifacts the pipeline actually produced -- the model card JSON, the leakage
   audit, the economics, the drift report, the last retraining cycle -- so every
   number in it is the number that is really in the repo. Regenerate it and it is
   current by construction.

2. **Documentation completeness is a tested requirement.** ``check_artifacts``
   asserts that every governance artifact a reviewer (or an auditor, or the next
   engineer) needs is actually present. It runs in CI, so the docs cannot quietly
   rot while the code moves on.

Run it:  ``python -m lonestar.governance``          (writes docs/model_card.md)
         ``python -m lonestar.governance --check``  (exit 1 if anything is missing)
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

# Everything a reviewer needs to understand, audit, and operate this model.
# (path relative to the repo root, why it has to exist)
REQUIRED_ARTIFACTS: tuple[tuple[str, str], ...] = (
    ("models/model_card.json", "machine-readable model metadata and serving contract"),
    ("models/decision_policy.json", "the thresholds production actually decides with"),
    ("docs/leakage_audit_report.md", "proof the planted leaks were found and removed"),
    ("docs/feature_pipeline.md", "point-in-time feature definitions and guarantees"),
    ("docs/model_results.md", "model selection and honest offline metrics"),
    ("docs/economics_memo.md", "what the decision policy is worth in dollars"),
    ("docs/drift_monitoring.md", "how a regime change is detected without labels"),
    ("docs/retraining.md", "the last challenger/champion cycle and its verdict"),
    ("docs/runbook.md", "what a human does when the monitor alerts"),
    ("docs/decisions", "architecture decision records"),
)

# Optional: present after a full pipeline run, absent on a fresh clone.
GENERATED_REPORTS: tuple[str, ...] = (
    "reports/leakage_audit.json",
    "reports/drift_report.json",
    "reports/retraining_cycle.json",
)


@dataclass
class ArtifactCheck:
    present: list[str]
    missing: list[tuple[str, str]]

    @property
    def ok(self) -> bool:
        return not self.missing


def check_artifacts(root: Path | str = ".") -> ArtifactCheck:
    """Verify every required governance artifact exists."""
    root = Path(root)
    present: list[str] = []
    missing: list[tuple[str, str]] = []
    for rel, why in REQUIRED_ARTIFACTS:
        (present.append(rel) if (root / rel).exists() else missing.append((rel, why)))
    return ArtifactCheck(present=present, missing=missing)


def _load(path: Path) -> dict | None:
    """Read a JSON artifact, or return None if this stage has not been run."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def gather(root: Path | str = ".") -> dict:
    """Collect every artifact the model card is assembled from."""
    root = Path(root)
    return {
        "card": _load(root / "models/model_card.json"),
        "policy": _load(root / "models/decision_policy.json"),
        "audit": _load(root / "reports/leakage_audit.json"),
        "drift": _load(root / "reports/drift_report.json"),
        "retraining": _load(root / "reports/retraining_cycle.json"),
    }


def _fmt(value, spec: str = "", fallback: str = "_not yet generated_") -> str:
    """Format a value, degrading gracefully when a stage has not been run."""
    if value is None:
        return fallback
    return format(value, spec) if spec else str(value)


def render_model_card(data: dict) -> str:
    """Assemble the human-readable model card from the gathered artifacts."""
    card = data.get("card") or {}
    policy = data.get("policy") or {}
    audit = data.get("audit") or {}
    drift = data.get("drift") or {}
    retrain = data.get("retraining") or {}

    holdout = card.get("holdout_metrics") or {}
    cost = policy.get("cost_model") or {}
    seg = policy.get("segment_thresholds") or {}
    decision = retrain.get("decision") or {}

    seg_rows = [f"| {name} | {value:.4f} |" for name, value in sorted(seg.items())] or [
        "| _none_ | _policy not yet generated_ |"
    ]

    return "\n".join(
        [
            "# Model Card — Lonestar Card Services Fraud Detection",
            "",
            "> Auto-generated by `python -m lonestar.governance` from the artifacts in "
            "this repository. Every number below is read from a file the pipeline "
            "actually produced, so this card cannot drift from reality. "
            f"Generated {datetime.now(UTC).isoformat(timespec='seconds')}.",
            "",
            "## Model details",
            "",
            f"- **Type**: {_fmt(card.get('model_kind'))} "
            "(gradient-boosted trees; see ADR 0002)",
            f"- **Trained**: {_fmt(card.get('trained_at_utc'))}",
            f"- **Features**: {len(card.get('feature_columns') or [])} point-in-time "
            "features (see `docs/feature_pipeline.md`)",
            f"- **Training window**: {_fmt((card.get('training_window') or {}).get('cutoff'))} "
            f"({_fmt((card.get('training_window') or {}).get('n_train'), ',')} rows)",
            f"- **Primary metric**: {_fmt(card.get('primary_metric'))}",
            "",
            "## Intended use",
            "",
            "- **In scope**: scoring individual card transactions for fraud risk at "
            "authorization time, and batch re-scoring of historical transactions.",
            "- **Users**: the fraud decisioning service (real time) and analytics/risk "
            "teams (batch).",
            "- **Out of scope**: credit decisions, account closure, law-enforcement "
            "referral, or any use where a score is treated as proof of wrongdoing. A "
            "score is a risk estimate, not a finding of fraud.",
            "",
            "## Performance",
            "",
            "Measured on a **held-out future window** — trained on the past, tested on "
            "what came after. Never a random split (see below).",
            "",
            "| Metric | Value |",
            "|---|---|",
            f"| PR-AUC (primary) | {_fmt(holdout.get('pr_auc'), '.4f')} |",
            f"| ROC-AUC | {_fmt(holdout.get('roc_auc'), '.4f')} |",
            f"| Test-window fraud prevalence | {_fmt(card.get('test_prevalence'), '.4%')} |",
            "",
            "PR-AUC is the headline because at well under 1% fraud, ROC-AUC flatters "
            "every model. Accuracy is meaningless here: predicting 'never fraud' would "
            "score ~99.5%.",
            "",
            "## Data leakage audit",
            "",
            "Three leaks were deliberately planted in the source data and then hunted "
            "down (see `docs/leakage_audit_report.md`):",
            "",
            "| Model | Test AUC |",
            "|---|---|",
            f"| With the leaks (a fantasy) | {_fmt(audit.get('auc_with_leaks'), '.4f')} |",
            f"| Without them (honest) | {_fmt(audit.get('auc_without_leaks'), '.4f')} |",
            f"| **Inflation from leakage** | **{_fmt(audit.get('auc_gap'), '+.4f')}** |",
            "",
            "Fraud labels arrive 30-60 days after the transaction, so a random "
            "train/test split leaks the future into training. Every split in this "
            "project is temporal.",
            "",
            "## Decision policy",
            "",
            "The model outputs a probability; the business needs a decision. Thresholds "
            "minimise **expected dollars**, not error count, and are tuned on a held-out "
            "calibration window (ADR 0004).",
            "",
            f"- A missed fraud costs the full transaction amount; a false decline costs "
            f"${_fmt(cost.get('fp_fixed'), '.0f')} + "
            f"{_fmt(cost.get('fp_rate'), '.0%')} of the amount.",
            f"- Global threshold: **{_fmt(policy.get('global_threshold'), '.4f')}**",
            "",
            f"| {_fmt(policy.get('segment_col'), fallback='segment')} | threshold |",
            "|---|---|",
            *seg_rows,
            "",
            "A threshold of 1.0 means *never decline* — in channels whose fraud is "
            "unpredictable background noise, intervening costs money and catches "
            "nothing. See `docs/economics_memo.md`.",
            "",
            "## Monitoring",
            "",
            f"- First drift ALERT in the current data: "
            f"**month {_fmt(drift.get('first_alert_month'))}**",
            f"- Population PSI ever reached the 'major' band: "
            f"**{_fmt(drift.get('population_psi_ever_major'))}**",
            "",
            "Monitoring is **label-free** by necessity: chargebacks are 30-60 days late, "
            "so the fraud rate cannot reveal a live attack. Detection watches the score "
            "tail *within each channel* against a control limit. Population-level drift "
            "metrics were tried first and **failed to detect the fraud ring at all** — a "
            "rare subpopulation is invisible in an average (ADR 0007).",
            "",
            "## Retraining",
            "",
            f"- Last cycle verdict: "
            f"**{'PROMOTE' if decision.get('promote') else 'HOLD' if decision else '_not yet run_'}**",
            f"- Label maturity gate: **{_fmt(retrain.get('label_maturity_days'))} days** — "
            "training never uses transactions whose chargebacks could still be in flight.",
            "",
            "A challenger is promoted only if it clears all three guardrails: enough "
            "fraud cases to decide on, a material PR-AUC improvement, and no channel "
            "regression. Otherwise the champion stays (ADR 0008).",
            "",
            "## Limitations and known risks",
            "",
            "- **The label delay is not solvable by modelling.** The monitor can flag an "
            "attack the day it starts, but a *retrained* model still waits ~60 days for "
            "chargebacks to mature. The gap is covered operationally — see "
            "`docs/runbook.md`.",
            "- **Merchant reputation points the wrong way during an attack.** A newly "
            "attacked merchant looks clean because its fraud has not been reported yet. "
            "The feature is kept (a tree model handles the non-monotonicity) and "
            "documented rather than silently dropped (`docs/feature_pipeline.md`).",
            "- **Segment thresholds encode a cost model, not a moral judgement.** If the "
            "assumed cost of a false decline is wrong — for example, if declining a "
            "customer causes harm the $ figure does not capture — the thresholds are "
            "wrong too. The cost model is a small JSON file precisely so it can be "
            "challenged and re-tuned without retraining.",
            "- **This model is trained on synthetic data** generated for this project. "
            "The engineering is production-shaped; the numbers are not a claim about any "
            "real portfolio.",
            "- **Rare-event metrics are noisy.** PR-AUC on a window with few frauds moves "
            "a lot; that is why promotion requires a minimum number of positives.",
            "",
            "## Fairness and ethical considerations",
            "",
            "- The model uses transaction and merchant behaviour only. It does not "
            "consume demographic attributes, and no proxy for them was engineered.",
            "- A false decline is a real harm to a real customer, which is why it carries "
            "an explicit cost and why the policy is measured on the false-decline rate, "
            "not only on fraud caught.",
            "- Every decision ships **reason codes** (per-feature contributions), so an "
            "adverse outcome can be explained rather than asserted.",
            "- Per-channel performance is tracked and a promotion is blocked if any "
            "channel regresses — an average must not improve at one group's expense.",
            "",
            "## Reproducing these numbers",
            "",
            "```bash",
            "python -m lonestar.generation --out data/raw",
            "python -m lonestar.audit      --data data/raw",
            "python -m lonestar.features   --data data/raw --out data/features",
            "python -m lonestar.modeling   --features data/features/features.parquet --out models",
            "python -m lonestar.decisions  --features data/features/features.parquet "
            "--raw data/raw --model models/fraud_model.joblib --out models",
            "python -m lonestar.monitoring --features data/features/features.parquet "
            "--raw data/raw --model models/fraud_model.joblib --out reports",
            "python -m lonestar.retraining --data data/raw --models models",
            "python -m lonestar.governance",
            "```",
            "",
        ]
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the model card / check artifacts (M10).")
    ap.add_argument("--root", default=".", help="Repository root.")
    ap.add_argument("--out", default="docs/model_card.md")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Only verify governance artifacts exist; exit 1 if any are missing.",
    )
    args = ap.parse_args()

    root = Path(args.root)
    result = check_artifacts(root)

    if args.check:
        for rel in result.present:
            print(f"  ok      {rel}")
        for rel, why in result.missing:
            print(f"  MISSING {rel}  -- {why}")
        if not result.ok:
            print(f"\n{len(result.missing)} governance artifact(s) missing.")
            sys.exit(1)
        print(f"\nAll {len(result.present)} governance artifacts present.")
        return

    out = root / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_model_card(gather(root)), encoding="utf-8")
    print(f"Wrote {out}")
    if result.missing:
        print(f"note: {len(result.missing)} governance artifact(s) still missing:")
        for rel, _ in result.missing:
            print(f"  - {rel}")


if __name__ == "__main__":
    main()
